spring:
  application:
    name: companies-crud_PROD
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: omarcs
    password: themassacre
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5