spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: omarcs_PROD
    password: themassacre_PROD
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5